### ISSUE TITLE
[service] docker compose container exits

### ISSUE THREAD

**Issue by practicalli-john** [practicalli/project-templates#10]
When running a project via `docker compose up --builld` the container exists with status zero

The container should continue to run and not exit until `docker compose down` is called (or `Ctrl`-`c` is pressed)

**Comment by practicalli-john** [comment]
The container is exiting with status 0, which means the container is okay. This suggests its running a command which exits and so the container shuts down.

Reviewing the `compose.yaml` file, there is a `command:` directive, which seems to be run instead of running the clojure service (via the command in the Dockerfile)

The command prints out the project name, so not important
```yaml
    environment:
      - COMPOSE_PROJECT_NAME
    command: echo "Build and run ${COMPOSE_PROJECT_NAME}"
```

Removing the `command:` directive resolves the issue and the container runs the Clojure service instead. 

It is assumed that `command:` is passed to the `Dockerfile` `ENTRYPOINT` directive and replaces the `CMD` that runs `java` (the Clojure service)
